mod macros;

// RUSTFIX define a macro which generates a whole `#[test]` block like this,
// with two variants: 1. ("xyz.ks", "default.bios.ks") and 2. ("xyz.prog.ks", "xyz.bios.ks").
#[test]
fn my_test() -> Result<(), kcpu::assembler::Error> {
    macros::run_test(None, include_str!(concat!("../../asm/test/", "alu.ks")))
}

// RUSTFIX make the autogenerated test a separate test in this directory, and pass the emitted source directly to the assembler.
