on: push

name: Continuous integration (platforms)

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features

      - uses: actions/upload-artifact@v2
        with:
          name: libkcpu.rlib
          path: target/release/libkcpu.rlib

      - uses: actions/upload-artifact@v2
        with:
          name: kcpu
          path: target/release/kcpu

      - uses: actions/upload-artifact@v2
        with:
          name: kasm
          path: target/release/kasm

      - uses: actions/upload-artifact@v2
        with:
          name: kcpu-vm
          path: target/release/kcpu-vm
