on: push

name: Continuous integration (platform binaries)

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features

      - name: build archive (windows)
        if: runner.os == 'Windows'
        run: tar -C target\\release -czf kcpu-target-${{ matrix.os }}.tar.gz libkcpu.rlib kcpu kasm kcpu-vm

      - name: build archive (non-windows)
        if: runner.os != 'Windows'
        run: tar -C target/release -czf kcpu-target-${{ matrix.os }}.tar.gz libkcpu.rlib kcpu kasm kcpu-vm

      - uses: actions/upload-artifact@v2
        with:
          path: kcpu-target-${{ matrix.os }}.tar.gz
